FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    g++ \
    python3 \
    openjdk-17-jdk-headless \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 sandboxuser

WORKDIR /box
RUN chown sandboxuser:sandboxuser /box

USER sandboxuser